// <auto-generated />
using System;
using KnowIT_TransportIT_webapp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KnowIT_TransportIT_webapp.Migrations.Passanger
{
    [DbContext(typeof(PassangerContext))]
    [Migration("20230817184626_InitialCreatePassanger")]
    partial class InitialCreatePassanger
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.21");

            modelBuilder.Entity("KnowIT_TransportIT_webapp.Models.PassangerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreationAccount")
                        .HasColumnType("TEXT");

                    b.Property<string>("PassangerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PassangerSocNo")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PassangerModel");
                });
#pragma warning restore 612, 618
        }
    }
}
